# Generated by Django 4.2.1 on 2023-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0010_remove_customuser_role_customuser_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Принята'), ('REJECTED', 'Отклонена'), ('CANCELED', 'Отменена'), ('CLOSED', 'Закрыта'), ('NEW', 'Новая')], default='NEW', max_length=250, null=True, verbose_name='статус заявки'),
        ),
    ]
