# Generated by Django 4.2.1 on 2023-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_alter_jobrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='employee',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='INN',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН сотрудника'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='employee_full_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ФИО сотрудника'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='personalized_request',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='именная заявка'),
        ),
    ]
