# Generated by Django 4.2.1 on 2023-06-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_remove_jobrequest_employee_jobrequest_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyShift',
            fields=[
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчет',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('telegram_bot.shift',),
        ),
    ]
