# Generated by Django 4.2.1 on 2023-06-08 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('FOR_DATE', 'На дату'), ('FOR_PERIOD', 'На период')], max_length=250, null=True, verbose_name='тип заявки'),
        ),
    ]
