# Generated by Django 4.2.1 on 2023-06-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0017_alter_employee_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestassignment',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата назначения'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrequestassignment',
            unique_together={('job_request', 'employee')},
        ),
    ]
