# Generated by Django 4.2.1 on 2023-06-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0018_alter_jobrequestassignment_assignment_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobrequestassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobrequestassignment',
            name='assignment_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата назначения'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrequestassignment',
            unique_together={('assignment_date', 'employee')},
        ),
    ]
