# Generated by Django 4.2.1 on 2023-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0019_alter_jobrequestassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='employee_position',
            field=models.CharField(blank=True, choices=[('KASSIR', 'Кассир'), ('POVAR', 'Повар')], max_length=300, null=True, verbose_name='должность'),
        ),
    ]
