# Generated by Django 4.2.1 on 2023-06-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0020_alter_jobrequest_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_job_request',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='текущая заявка'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_request_draft',
            field=models.JSONField(blank=True, null=True, verbose_name='драфт смен'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='employee_position',
            field=models.CharField(blank=True, choices=[('Кассир', 'Кассир'), ('Повар', 'Повар')], max_length=300, null=True, verbose_name='должность'),
        ),
    ]
