# Generated by Django 4.2.1 on 2023-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_alter_employee_current_job_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ФИО сотрудника'),
        ),
    ]
