# Generated by Django 4.2.1 on 2023-06-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0023_alter_employee_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='message_status',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='статус опроса'),
        ),
    ]
