# Generated by Django 4.2.1 on 2023-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0025_alter_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jumis_go_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID в Jumis Go'),
        ),
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='язык'),
        ),
    ]
