# Generated by Django 4.2.1 on 2023-07-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0026_employee_jumis_go_user_id_employee_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='token',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='язык'),
        ),
    ]
