# Generated by Django 4.2.1 on 2023-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0027_employee_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='токен'),
        ),
    ]
