# Generated by Django 4.2.1 on 2023-07-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0028_employee_password_alter_employee_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='город'),
        ),
    ]
