# Generated by Django 4.2.1 on 2023-07-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0029_employee_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='token',
            field=models.IntegerField(blank=True, null=True, verbose_name='токен'),
        ),
    ]
