# Generated by Django 4.2.1 on 2023-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0031_employeelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='id_number',
            field=models.CharField(max_length=20, verbose_name='ИИН'),
        ),
    ]
