# Generated by Django 4.2.1 on 2023-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0032_alter_employeelist_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeelist',
            name='id_number',
        ),
        migrations.AddField(
            model_name='employeelist',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
