# Generated by Django 4.2.1 on 2023-07-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0033_remove_employeelist_id_number_employeelist_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.IntegerField(blank=True, max_length=50, null=True, unique=True, verbose_name='город'),
        ),
    ]
