# Generated by Django 4.2.1 on 2023-07-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0034_alter_employee_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.IntegerField(blank=True, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='язык'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='пароль'),
        ),
    ]
