# Generated by Django 4.2.1 on 2023-07-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0035_alter_employee_city_alter_employee_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID телеграм чата'),
        ),
    ]
