# Generated by Django 4.2.1 on 2023-07-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0038_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeList',
            new_name='Training',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='название вакансии'),
        ),
    ]
