# Generated by Django 4.2.1 on 2023-07-10 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0039_rename_employeelist_training_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='INN',
            new_name='IIN',
        ),
        migrations.RenameField(
            model_name='jobrequest',
            old_name='INN',
            new_name='IIN',
        ),
        migrations.RenameField(
            model_name='training',
            old_name='inn',
            new_name='iin',
        ),
    ]
