# Generated by Django 4.2.1 on 2023-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0040_rename_inn_employee_iin_rename_inn_jobrequest_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vacancy_id_draft',
            field=models.IntegerField(blank=True, null=True, verbose_name='id вакансии'),
        ),
    ]
